#dev port
server.port=8761

#security
spring.security.user.name=admin
spring.security.user.password=1234

#eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost
eureka.server.enable-self-preservation=false

#Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#Debug
logging.level.com.netflix.eureka=INFO
logging.level.org.springframework.cloud.netflix.eureka=INFO